### ISSUE TITLE
TTY initialization failed

### ISSUE THREAD

**Issue by Sakethtadimeti** [Nutlope/aicommits#223]
### Bug description

Configured a prepare-commit-msg hook that runs `aicommits --type conventional`.

Expected: 
Provide AI commit messages

Actual:
Throws the attached error

```
◇  Detected 2 staged files:
     .husky/prepare-commit-msg
     package.json
│
◇  Changes analyzed
│
└  ✖ TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)

    at new SystemError (node:internal/errors:238:5)
    at new NodeError (node:internal/errors:349:7)
    at new WriteStream (node:tty:94:11)
    at ri.prompt (file:///usr/local/lib/node_modules/aicommits/dist/cli.mjs:29:700)
    at fi (file:///usr/local/lib/node_modules/aicommits/dist/cli.mjs:39:7)
    at file:///usr/local/lib/node_modules/aicommits/dist/cli.mjs:81:506
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    aicommits v1.11.0
```

### aicommits version

1.11.0

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 36.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/opt/node@16/bin/npm
    Watchman: 2023.05.01.00 - /usr/local/bin/watchman
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by Sakethtadimeti** [comment]
Seems to be failing with/without hook

**Comment by privatenumber** [comment]
The TTY issues are caused by your network settings. AFAIK, there's nothing we can do about it in aicommits.

**Comment by danielbayley** [comment]
> The TTY issues are caused by your network settings. AFAIK, there's nothing we can do about it in aicommits.

@privatenumber How so? I have the same issue with the hook (but the command works when called directly…) @Sakethtadimeti Did you find a solution?

~~~ sh
┌   aicommits 
│
◇  Detected 1 staged file:
     .gitignore
│
◇  Changes analyzed
│
└  ✖ TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)

    at new SystemError (node:internal/errors:257:5)
    at new NodeError (node:internal/errors:368:7)
    at new WriteStream (node:tty:93:11)
    at ri.prompt (file:///Users/Dan/Work/dev/npm/create-npm-package/node_modules/.pnpm/aicommits@1.11.0/node_modules/aicommits/dist/cli.mjs:29:700)
    at fi (file:///Users/Dan/Work/dev/npm/create-npm-package/node_modules/.pnpm/aicommits@1.11.0/node_modules/aicommits/dist/cli.mjs:39:7)
    at file:///Users/Dan/Work/dev/npm/create-npm-package/node_modules/.pnpm/aicommits@1.11.0/node_modules/aicommits/dist/cli.mjs:81:506
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    aicommits v1.11.0
~~~

**Comment by stevemao** [comment]
> The TTY issues are caused by your network settings. AFAIK, there's nothing we can do about it in aicommits.

@privatenumber How is that related to network settings. Can you please elaborate?
