### ISSUE TITLE
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

### ISSUE THREAD

**Issue by waki285** [Nutlope/aicommits#229]
### Bug description

I got this error. Full log:
```sh
┌   aicommits 
│
◇  Detected 1 staged file:
     src/logger.ts
│
◇  Changes analyzed
│
◇  Use this commit message?

   Add logger configuration function

│  Yes
│
└  ✖ Command failed with exit code 128: git commit -m Add logger configuration function 
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
    at Su (file:///C:/Users/[redacted]/AppData/Roaming/nvm/v16.15.0/node_modules/aicommits/dist/cli.mjs:27:57)
    at file:///C:/Users/[redacted]/AppData/Roaming/nvm/v16.15.0/node_modules/aicommits/dist/cli.mjs:27:8640
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/[redacted]/AppData/Roaming/nvm/v16.15.0/node_modules/aicommits/dist/cli.mjs:84:221

    aicommits v1.11.0

    Please open a Bug report with the information above:
    https://github.com/Nutlope/aicommits/issues/new/choose
```

I have done this operation:
1. create and edit `src/logger.ts`
2. `git add src/logger.ts`
3. `aicommits`

### aicommits version

v1.11.0

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.74 GB / 15.75 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.1.1 - C:\Program Files\nodejs\pnpm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by waki285** [comment]
This error occurred when I tried again (or rather, it occurred in all of the several edits I made down the road)

**Comment by waki285** [comment]
this did not happen at the command prompt or in WSL(2)
