### ISSUE TITLE
Error: spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by spidy0x0** [Nutlope/aicommits#26]
i ```git init``` on an existing project 
```git add .```
then run ```aicommits```

```logs
▲ Welcome to AICommits!
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1119:20)
    at spawnSync (node:child_process:847:24)
    at execSync (node:child_process:927:15)
    at /usr/local/lib/node_modules/aicommits/bin/aicommits.js:40:51
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/aicommits/bin/aicommits.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/aicommits/bin/aicommits.js:5:12)
    at main (/usr/local/lib/node_modules/aicommits/bin/aicommits.js:23:12)
    at /usr/local/lib/node_modules/aicommits/bin/index.js:15:32 {
  errno: -105,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    'git diff --cached . ":(exclude)package-lock.json" ":(exclude)yarn.lock" ":(exclude)pnpm-lock.yaml"'
  ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    'diff --git a/app.js b/app.js\n' +
      'new file mode 100644\n' +
      'index 0000000..2d0a470\n' +
      '--- /dev/null\n' +
      '+++ b/app.js\n' +
      '@@ -0,0 +1,73 @@\n' +
      "+const axios = require('axios');\n" +
      "+const fs = require('fs');\n" +
      "+const path = require('path');\n" +
      '+\n' +
      '+async function getData(url) {\n' +
      '+    const response = await axios.get(url);\n' +
      '+    return response.data;\n' +
      '+}\n' +
      '+\n' +
      '+async function downloadImage(url, filename) {\n' +
      '+  const response = await axios.get(url, {\n' +
      "+    responseType: 'stream'\n" +
      '+  });\n' +
      '+  response.data.pipe(fs.createWriteStream(filename));\n' +
      '+  console.log(`downloaded ${filename}`);\n' +
      '+}\n' +
      '+\n' +
      '+let next = 40106098;\n' +
      '+\n' +
      '+  async function getImgs(){\n' +
      '+        const initialUrl = `https://www.wwe.com/api/gallery/${next}/0/0/0`;\n' +
      '+        const initialData = await getData(initialUrl);\n' +
      '+        const totalImages = initialData.total_images;\n' +
      '+\n' +
      "+        const updatedUrl = initialUrl.replace('/0/', `/${totalImages}/`);\n" +
      '+        const updatedData = await getData(updatedUrl);\n' +
      '+        // console.log(updatedData);\n' +
      '+        let {\n' +
      '+            photos\n' +
      '+        } = updatedData;\n' +
      '+\n' +
      '+        next = updatedData.next_gallery;\n' +
      '+\n' +
      '+        const regex = /src="(.*?)"/;\n' +
      '+\n' +
      '+        const srcValues = photos.map(({\n' +
      '+            photo\n' +
      '+        }) => {\n' +
      '+            const match = photo.match(regex);\n' +
      "+            return 'https://www.wwe.com'+match[1];\n" +
      '+        });\n' +
      '+\n' +
      '+        console.log(srcValues);\n' +
      '+\n' +
      '+\n' +
      '+        //download images\n' +
      '+        const folderName = updatedData.title;\n' +
      '+        if (!fs.existsSync(folderName)) {\n' +
      '+          fs.mkdirSync(folderName);\n' +
      '+        }\n' +
      '+      \n' +
      '+        let promises = [];\n' +
      '+        srcValues.forEach((photo, index) => {\n' +
      '+          const filename = path.join(folderName, `photo-${index}.jpg`);\n' +
      '+          setTimeout(() => {\n' +
      '+            promises.push(downloadImage(photo, filename));\n' +
      '+          }, 1000);\n' +
      '+        });\n' +
      '+\n' +
      '+        await Promise.all(promises)\n' +
      '+        .then(() => {\n' +
      '+            console.log("All images have been downloaded.");\n' +
      '+            if (next) {\n' +
      '+              setTimeout(() => {\n' +
      '+                getImgs();\n' +
      '+              }, 3000);\n' +
      '+            } else {\n' +
      '+                console.log("No more galleries to download.")\n' +
      '+            }\n' +
      '+        });\n' +
      '+  };\n' +
      '+\n' +
      '+  getImgs();\n' +
      'diff --git a/node_modules/.bin/playwright b/node_modules/.bin/playwright\n' +
      'new file mode 120000\n' +
      'index 0000000..50992a7\n' +
      '--- /dev/null\n' +
      '+++ b/node_modules/.bin/playwright\n' +
      '@@ -0,0 +1 @@\n' +
      '+../playwright/cli.js\n' +
      '\\ No newline at end of file\n' +
      'diff --git a/node_modules/.package-lock.json b/node_modules/.package-lock.json\n' +
      'new file mode 100644\n' +
      'index 0000000..1db02d8\n' +
      '--- /dev/null\n' +
      '+++ b/node_modules/.package-lock.json\n' +
      '@@ -0,0 +1,124 @@\n' +
      '+{\n' +
      '+  "name": "wwescrapper",\n' +
      '+  "version": "1.0.0",\n' +
      '+  "lockfileVersion": 3,\n' +
      '+  "requires": true,\n' +
      '+  "packages": {\n' +
      '+    "node_modules/asynckit": {\n' +
      '+      "version": "0.4.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz",\n' +
      '+      "integrity": "sha512-Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q=="\n' +
      '+    },\n' +
      '+    "node_modules/axios": {\n' +
      '+      "version": "1.3.1",\n' +
      '+      "resolved": "https://registry.npmjs.org/axios/-/axios-1.3.1.tgz",\n' +
      '+      "integrity": "sha512-78pWJsQTceInlyaeBQeYZ/QgZeWS8hGeKiIJiDKQe3hEyBb7sEMq0K4gjx+Va6WHTYO4zI/RRl8qGRzn0YMadA==",\n' +
      '+      "dependencies": {\n' +
      '+        "follow-redirects": "^1.15.0",\n' +
      '+        "form-data": "^4.0.0",\n' +
      '+        "proxy-from-env": "^1.1.0"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/combined-stream": {\n' +
      '+      "version": "1.0.8",\n' +
      '+      "resolved": "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz",\n' +
      '+      "integrity": "sha512-FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==",\n' +
      '+      "dependencies": {\n' +
      '+        "delayed-stream": "~1.0.0"\n' +
      '+      },\n' +
      '+      "engines": {\n' +
      '+        "node": ">= 0.8"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/delayed-stream": {\n' +
      '+      "version": "1.0.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz",\n' +
      '+      "integrity": "sha512-ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==",\n' +
      '+      "engines": {\n' +
      '+        "node": ">=0.4.0"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/follow-redirects": {\n' +
      '+      "version": "1.15.2",\n' +
      '+      "resolved": "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.2.tgz",\n' +
      '+      "integrity": "sha512-VQLG33o04KaQ8uYi2tVNbdrWp1QWxNNea+nmIB4EVM28v0hmP17z7aG1+wAkNzVq4KeXTq3221ye5qTJP91JwA==",\n' +
      '+      "funding": [\n' +
      '+        {\n' +
      '+          "type": "individual",\n' +
      '+          "url": "https://github.com/sponsors/RubenVerborgh"\n' +
      '+        }\n' +
      '+      ],\n' +
      '+      "engines": {\n' +
      '+        "node": ">=4.0"\n' +
      '+      },\n' +
      '+      "peerDependenciesMeta": {\n' +
      '+        "debug": {\n' +
      '+          "optional": true\n' +
      '+        }\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/form-data": {\n' +
      '+      "version": "4.0.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",\n' +
      '+      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",\n' +
      '+      "dependencies": {\n' +
      '+        "asynckit": "^0.4.0",\n' +
      '+        "combined-stream": "^1.0.8",\n' +
      '+        "mime-types": "^2.1.12"\n' +
      '+      },\n' +
      '+      "engines": {\n' +
      '+        "node": ">= 6"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/mime-db": {\n' +
      '+      "version": "1.52.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz",\n' +
      '+      "integrity": "sha512-sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==",\n' +
      '+      "engines": {\n' +
      '+        "node": ">= 0.6"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/mime-types": {\n' +
      '+      "version": "2.1.35",\n' +
      '+      "resolved": "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz",\n' +
      '+      "integrity": "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==",\n' +
      '+      "dependencies": {\n' +
      '+        "mime-db": "1.52.0"\n' +
      '+      },\n' +
      '+      "engines": {\n' +
      '+        "node": ">= 0.6"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/playwright": {\n' +
      '+      "version": "1.30.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/playwright/-/playwright-1.30.0.tgz",\n' +
      '+      "integrity": "sha512-ENbW5o75HYB3YhnMTKJLTErIBExrSlX2ZZ1C/FzmHjUYIfxj/UnI+DWpQr992m+OQVSg0rCExAOlRwB+x+yyIg==",\n' +
      '+      "hasInstallScript": true,\n' +
      '+      "dependencies": {\n' +
      '+        "playwright-core": "1.30.0"\n' +
      '+      },\n' +
      '+      "bin": {\n' +
      '+        "playwright": "cli.js"\n' +
      '+      },\n' +
      '+      "engines": {\n' +
      '+        "node": ">=14"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/playwright-core": {\n' +
      '+      "version": "1.30.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/playwright-core/-/playwright-core-1.30.0.tgz",\n' +
      '+      "integrity": "sha512-7AnRmTCf+GVYhHbLJsGUtskWTE33SwMZkybJ0v6rqR1boxq2x36U7p1vDRV7HO2IwTZgmycracLxPEJI49wu4g==",\n' +
      '+      "bin": {\n' +
      '+        "playwright": "cli.js"\n' +
      '+      },\n' +
      '+      "engines": {\n' +
      '+        "node": ">=14"\n' +
      '+      }\n' +
      '+    },\n' +
      '+    "node_modules/proxy-from-env": {\n' +
      '+      "version": "1.1.0",\n' +
      '+      "resolved": "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz",\n' +
      '+      "integrity": "sha512-D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg=="\n' +
      '+    }\n' +
      '+  }\n' +
      '+}\n' +
      'diff --git a/node_modules/asynckit/LICENSE b/node_modules/asynckit/LICENSE\n' +
      'new file mode 100644\n' +
      'index 0000000..c9eca5d\n' +
      '--- /dev/null\n' +
      '+++ b/node_modules/asynckit/LICENSE\n' +
      '@@ -0,0 +1,21 @@\n' +
      '+The MIT License (MIT)\n' +
      '+\n' +
      '+Copyright (c) 2016 Alex Indigo\n' +
      '+\n' +
      '+Permission is hereby granted, free of charge, to any person obtaining a copy\n' +
      '+of this software and associated documentation files (the "Software"), to deal\n' +
      '+in the Software without restriction, including without limitation the rights\n' +
      '+to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n' +
      '+copies of the Software, and to permit persons to whom the Software is\n' +
      '+furnished to do so, subject to the following conditions:\n' +
      '+\n' +
      '+The above copyright notice and this permission notice shall be included in all\n' +
      '+copies or substantial portions of the Software.\n' +
      '+\n' +
      '+THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n' +
      '+IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n' +
      '+FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n' +
      '+AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n' +
      '+LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n' +
      '+OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n' +
      '+SOFTWARE.\n' +
      'diff --git a/node_modules/asynckit/README.md b/node_modules/asynckit/README.md\n' +
      'new file mode 100644\n' +
      'index 0000000..ddcc7e6\n' +
      '--- /dev/null\n' +
      '+++ b/node_modules/asynckit/README.md\n' +
      '@@ -0,0 +1,233 @@\n' +
      '+# asynckit [![NPM Module](https://img.shields.io/npm/v/asynckit.svg?style=flat)](https://www.npmjs.com/package/asynckit)\n' +
      '+\n' +
      '+Minimal async jobs utility library, with streams support.\n' +
      '+\n' +
      '+[![PhantomJS Build](https://img.shields.io/travis/alexindigo/asynckit/v0.4.0.svg?label=browser&style=flat)](https://travis-ci.org/alexindigo/asynckit)\n' +
      '+[![Linux Build](https://img.shields.io/travis/alexindigo/asynckit/v0.4.0.svg?label=linux:0.12-6.x&style=flat)](https://travis-ci.org/alexindigo/asynckit)\n' +
      '+[![Windows Build](https://img.shields.io/appveyor/ci/alexindigo/asynckit/v0.4.0.svg?label=windows:0.12-6.x&style=flat)](https://ci.appveyor.com/project/alexindigo/asynckit)\n' +
      '+\n' +
      '+[![Coverage Status](https://img.shields.io/coveralls/alexindigo/asynckit/v0.4.0.svg?label=code+coverage&style=flat)](https://coveralls.io/github/alexindigo/asynckit?branch=master)\n' +
      '+[![Dependency Status](https://img.shields.io/david/alexindigo/asynckit/v0.4.0.svg?style=flat)](https://david-dm.org/alexindigo/asynckit)\n' +
      '+[![bitHound Overall Score](https://www.bithound.io/github/alexindigo/asynckit/badges/score.svg)](https://www.bithound.io/github/alexindigo/asynckit)\n' +
      '+\n' +
      '+<!-- [![Readme](https://img.shields.io/badge/readme-tested-brightgreen.svg?style=flat)](https://www.npmjs.com/package/reamde) -->\n' +
      '+\n' +
      '+AsyncKit provides harness for `parallel` and `serial` iterators over list of items represented by arrays or objects.\n' +
      '+Optionally it accepts abort function (should be synchronously return by iterator for each ite'... 1079464 more characters,
    ''
  ],
  pid: 620400,
  stdout: 'diff --git a/app.js b/app.js\n' +
    'new file mode 100644\n' +
    'index 0000000..2d0a470\n' +
    '--- /dev/null\n' +
    '+++ b/app.js\n' +
    '@@ -0,0 +1,73 @@\n' +
    "+const axios = require('axios');\n" +
    "+const fs = require('fs');\n" +
    "+const path = require('path');\n" +
    '+\n' +
    '+async function getData(url) {\n' +
    '+    const response = await axios.get(url);\n' +
    '+    return response.data;\n' +
    '+}\n' +
    '+\n' +
    '+async function downloadImage(url, filename) {\n' +
    '+  const response = await axios.get(url, {\n' +
    "+    responseType: 'stream'\n" +
    '+  });\n' +
    '+  response.data.pipe(fs.createWriteStream(filename));\n' +
    '+  console.log(`downloaded ${filename}`);\n' +
    '+}\n' +
    '+\n' +
    '+let next = 40106098;\n' +
    '+\n' +
    '+  async function getImgs(){\n' +
    '+        const initialUrl = `https://www.wwe.com/api/gallery/${next}/0/0/0`;\n' +
    '+        const initialData = await getData(initialUrl);\n' +
    '+        const totalImages = initialData.total_images;\n' +
    '+\n' +
    "+        const updatedUrl = initialUrl.replace('/0/', `/${totalImages}/`);\n" +
    '+        const updatedData = await getData(updatedUrl);\n' +
    '+        // console.log(updatedData);\n' +
    '+        let {\n' +
    '+            photos\n' +
    '+        } = updatedData;\n' +
    '+\n' +
    '+        next = updatedData.next_gallery;\n' +
    '+\n' +
    '+        const regex = /src="(.*?)"/;\n' +
    '+\n' +
    '+        const srcValues = photos.map(({\n' +
    '+            photo\n' +
    '+        }) => {\n' +
    '+            const match = photo.match(regex);\n' +
    "+            return 'https://www.wwe.com'+match[1];\n" +
    '+        });\n' +
    '+\n' +
    '+        console.log(srcValues);\n' +
    '+\n' +
    '+\n' +
    '+        //download images\n' +
    '+        const folderName = updatedData.title;\n' +
    '+        if (!fs.existsSync(folderName)) {\n' +
    '+          fs.mkdirSync(folderName);\n' +
    '+        }\n' +
    '+      \n' +
    '+        let promises = [];\n' +
    '+        srcValues.forEach((photo, index) => {\n' +
    '+          const filename = path.join(folderName, `photo-${index}.jpg`);\n' +
    '+          setTimeout(() => {\n' +
    '+            promises.push(downloadImage(photo, filename));\n' +
    '+          }, 1000);\n' +
    '+        });\n' +
    '+\n' +
    '+        await Promise.all(promises)\n' +
    '+        .then(() => {\n' +
    '+            console.log("All images have been downloaded.");\n' +
    '+            if (next) {\n' +
    '+              setTimeout(() => {\n' +
    '+                getImgs();\n' +
    '+              }, 3000);\n' +
    '+            } else {\n' +
    '+                console.log("No more galleries to download.")\n' +
    '+            }\n' +
    '+        });\n' +
    '+  };\n' +
    '+\n' +
    '+  getImgs();\n' +
    'diff --git a/node_modules/.bin/playwright b/node_modules/.bin/playwright\n' +
    'new file mode 120000\n' +
    'index 0000000..50992a7\n' +
    '--- /dev/null\n' +
    '+++ b/node_modules/.bin/playwright\n' +
    '@@ -0,0 +1 @@\n' +
    '+../playwright/cli.js\n' +
    '\\ No newline at end of file\n' +
    'diff --git a/node_modules/.package-lock.json b/node_modules/.package-lock.json\n' +
    'new file mode 100644\n' +
    'index 0000000..1db02d8\n' +
    '--- /dev/null\n' +
    '+++ b/node_modules/.package-lock.json\n' +
    '@@ -0,0 +1,124 @@\n' +
    '+{\n' +
    '+  "name": "wwescrapper",\n' +
    '+  "version": "1.0.0",\n' +
    '+  "lockfileVersion": 3,\n' +
    '+  "requires": true,\n' +
    '+  "packages": {\n' +
    '+    "node_modules/asynckit": {\n' +
    '+      "version": "0.4.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz",\n' +
    '+      "integrity": "sha512-Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q=="\n' +
    '+    },\n' +
    '+    "node_modules/axios": {\n' +
    '+      "version": "1.3.1",\n' +
    '+      "resolved": "https://registry.npmjs.org/axios/-/axios-1.3.1.tgz",\n' +
    '+      "integrity": "sha512-78pWJsQTceInlyaeBQeYZ/QgZeWS8hGeKiIJiDKQe3hEyBb7sEMq0K4gjx+Va6WHTYO4zI/RRl8qGRzn0YMadA==",\n' +
    '+      "dependencies": {\n' +
    '+        "follow-redirects": "^1.15.0",\n' +
    '+        "form-data": "^4.0.0",\n' +
    '+        "proxy-from-env": "^1.1.0"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/combined-stream": {\n' +
    '+      "version": "1.0.8",\n' +
    '+      "resolved": "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz",\n' +
    '+      "integrity": "sha512-FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==",\n' +
    '+      "dependencies": {\n' +
    '+        "delayed-stream": "~1.0.0"\n' +
    '+      },\n' +
    '+      "engines": {\n' +
    '+        "node": ">= 0.8"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/delayed-stream": {\n' +
    '+      "version": "1.0.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz",\n' +
    '+      "integrity": "sha512-ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==",\n' +
    '+      "engines": {\n' +
    '+        "node": ">=0.4.0"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/follow-redirects": {\n' +
    '+      "version": "1.15.2",\n' +
    '+      "resolved": "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.2.tgz",\n' +
    '+      "integrity": "sha512-VQLG33o04KaQ8uYi2tVNbdrWp1QWxNNea+nmIB4EVM28v0hmP17z7aG1+wAkNzVq4KeXTq3221ye5qTJP91JwA==",\n' +
    '+      "funding": [\n' +
    '+        {\n' +
    '+          "type": "individual",\n' +
    '+          "url": "https://github.com/sponsors/RubenVerborgh"\n' +
    '+        }\n' +
    '+      ],\n' +
    '+      "engines": {\n' +
    '+        "node": ">=4.0"\n' +
    '+      },\n' +
    '+      "peerDependenciesMeta": {\n' +
    '+        "debug": {\n' +
    '+          "optional": true\n' +
    '+        }\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/form-data": {\n' +
    '+      "version": "4.0.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",\n' +
    '+      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",\n' +
    '+      "dependencies": {\n' +
    '+        "asynckit": "^0.4.0",\n' +
    '+        "combined-stream": "^1.0.8",\n' +
    '+        "mime-types": "^2.1.12"\n' +
    '+      },\n' +
    '+      "engines": {\n' +
    '+        "node": ">= 6"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/mime-db": {\n' +
    '+      "version": "1.52.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz",\n' +
    '+      "integrity": "sha512-sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==",\n' +
    '+      "engines": {\n' +
    '+        "node": ">= 0.6"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/mime-types": {\n' +
    '+      "version": "2.1.35",\n' +
    '+      "resolved": "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz",\n' +
    '+      "integrity": "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==",\n' +
    '+      "dependencies": {\n' +
    '+        "mime-db": "1.52.0"\n' +
    '+      },\n' +
    '+      "engines": {\n' +
    '+        "node": ">= 0.6"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/playwright": {\n' +
    '+      "version": "1.30.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/playwright/-/playwright-1.30.0.tgz",\n' +
    '+      "integrity": "sha512-ENbW5o75HYB3YhnMTKJLTErIBExrSlX2ZZ1C/FzmHjUYIfxj/UnI+DWpQr992m+OQVSg0rCExAOlRwB+x+yyIg==",\n' +
    '+      "hasInstallScript": true,\n' +
    '+      "dependencies": {\n' +
    '+        "playwright-core": "1.30.0"\n' +
    '+      },\n' +
    '+      "bin": {\n' +
    '+        "playwright": "cli.js"\n' +
    '+      },\n' +
    '+      "engines": {\n' +
    '+        "node": ">=14"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/playwright-core": {\n' +
    '+      "version": "1.30.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/playwright-core/-/playwright-core-1.30.0.tgz",\n' +
    '+      "integrity": "sha512-7AnRmTCf+GVYhHbLJsGUtskWTE33SwMZkybJ0v6rqR1boxq2x36U7p1vDRV7HO2IwTZgmycracLxPEJI49wu4g==",\n' +
    '+      "bin": {\n' +
    '+        "playwright": "cli.js"\n' +
    '+      },\n' +
    '+      "engines": {\n' +
    '+        "node": ">=14"\n' +
    '+      }\n' +
    '+    },\n' +
    '+    "node_modules/proxy-from-env": {\n' +
    '+      "version": "1.1.0",\n' +
    '+      "resolved": "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz",\n' +
    '+      "integrity": "sha512-D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg=="\n' +
    '+    }\n' +
    '+  }\n' +
    '+}\n' +
    'diff --git a/node_modules/asynckit/LICENSE b/node_modules/asynckit/LICENSE\n' +
    'new file mode 100644\n' +
    'index 0000000..c9eca5d\n' +
    '--- /dev/null\n' +
    '+++ b/node_modules/asynckit/LICENSE\n' +
    '@@ -0,0 +1,21 @@\n' +
    '+The MIT License (MIT)\n' +
    '+\n' +
    '+Copyright (c) 2016 Alex Indigo\n' +
    '+\n' +
    '+Permission is hereby granted, free of charge, to any person obtaining a copy\n' +
    '+of this software and associated documentation files (the "Software"), to deal\n' +
    '+in the Software without restriction, including without limitation the rights\n' +
    '+to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n' +
    '+copies of the Software, and to permit persons to whom the Software is\n' +
    '+furnished to do so, subject to the following conditions:\n' +
    '+\n' +
    '+The above copyright notice and this permission notice shall be included in all\n' +
    '+copies or substantial portions of the Software.\n' +
    '+\n' +
    '+THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n' +
    '+IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n' +
    '+FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n' +
    '+AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n' +
    '+LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n' +
    '+OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n' +
    '+SOFTWARE.\n' +
    'diff --git a/node_modules/asynckit/README.md b/node_modules/asynckit/README.md\n' +
    'new file mode 100644\n' +
    'index 0000000..ddcc7e6\n' +
    '--- /dev/null\n' +
    '+++ b/node_modules/asynckit/README.md\n' +
    '@@ -0,0 +1,233 @@\n' +
    '+# asynckit [![NPM Module](https://img.shields.io/npm/v/asynckit.svg?style=flat)](https://www.npmjs.com/package/asynckit)\n' +
    '+\n' +
    '+Minimal async jobs utility library, with streams support.\n' +
    '+\n' +
    '+[![PhantomJS Build](https://img.shields.io/travis/alexindigo/asynckit/v0.4.0.svg?label=browser&style=flat)](https://travis-ci.org/alexindigo/asynckit)\n' +
    '+[![Linux Build](https://img.shields.io/travis/alexindigo/asynckit/v0.4.0.svg?label=linux:0.12-6.x&style=flat)](https://travis-ci.org/alexindigo/asynckit)\n' +
    '+[![Windows Build](https://img.shields.io/appveyor/ci/alexindigo/asynckit/v0.4.0.svg?label=windows:0.12-6.x&style=flat)](https://ci.appveyor.com/project/alexindigo/asynckit)\n' +
    '+\n' +
    '+[![Coverage Status](https://img.shields.io/coveralls/alexindigo/asynckit/v0.4.0.svg?label=code+coverage&style=flat)](https://coveralls.io/github/alexindigo/asynckit?branch=master)\n' +
    '+[![Dependency Status](https://img.shields.io/david/alexindigo/asynckit/v0.4.0.svg?style=flat)](https://david-dm.org/alexindigo/asynckit)\n' +
    '+[![bitHound Overall Score](https://www.bithound.io/github/alexindigo/asynckit/badges/score.svg)](https://www.bithound.io/github/alexindigo/asynckit)\n' +
    '+\n' +
    '+<!-- [![Readme](https://img.shields.io/badge/readme-tested-brightgreen.svg?style=flat)](https://www.npmjs.com/package/reamde) -->\n' +
    '+\n' +
    '+AsyncKit provides harness for `parallel` and `serial` iterators over list of items represented by arrays or objects.\n' +
    '+Optionally it accepts abort function (should be synchronously return by iterator for each ite'... 1079464 more characters,
  stderr: ''
}

```

**Comment by spenserblack** [comment]
>`diff --git a/node_modules/asynckit/README.md b/node_modules/asynckit/README.md\n`

(and others)

It looks like you have `node_modules` tracked. Perhaps the size of the diff was too large for the buffer?

**Comment by spidyhackx** [comment]
yeah , that was the issue. thanks
