### ISSUE TITLE
aicommit un ubuntu for windows (WSL2) python version 3.10

### ISSUE THREAD

**Issue by AikawaKai** [Nutlope/aicommits#68]
I did install aicommit in ubuntu for windows, using python 3.10, but I got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aicommit", line 5, in <module>
    from autocommit.commit import main
  File "/usr/local/lib/python3.10/dist-packages/autocommit/commit.py", line 2, in <module>
    from PyInquirer import prompt as py_inquirer_prompt, style_from_dict, Token
  File "/usr/local/lib/python3.10/dist-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

This is caused by a change in the collections interface starting with Python 3.10. To solve the issue for now it is possible to:

- Revert to Python 3.9.
- Patch the code manually

is it possible to make the library compatible with python 3.10?

**Comment by privatenumber** [comment]
Confused by this issue. This is not a Python project.

**Comment by Nutlope** [comment]
Agreed with prvatenumber, I think you have the wrong project @AikawaKai. Closing for now, feel free to follow up here though

**Comment by AikawaKai** [comment]
> Agreed with prvatenumber, I think you have the wrong project @AikawaKai. Closing for now, feel free to follow up here though

I am so sorry. I think so. Feel free to delete the issue
